### ISSUE TITLE
cream:full_config error: no such file to load -- rspec/core (LoadError)

### ISSUE THREAD

**Issue by stylpe** [kristianmandrup/cream#27]
Running full_config without any arguments breaks with this stack trace:

```
$ rails g cream:full_config
d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/r3_plugin_toolbox-0.4.2/lib/r3_plugin_toolbox/rspec/config.rb:1:in `require': no such file to load -- rspec/core (LoadError)
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/r3_plugin_toolbox-0.4.2/lib/r3_plugin_toolbox/rspec/config.rb:1:in `<top (required)>'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/require_all-1.2.0/lib/require_all.rb:109:in `require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/require_all-1.2.0/lib/require_all.rb:109:in `block in require_all'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/require_all-1.2.0/lib/require_all.rb:107:in `each'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/require_all-1.2.0/lib/require_all.rb:107:in `require_all'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/r3_plugin_toolbox-0.4.2/lib/r3_plugin_toolbox/main.rb:5:in `<top (required)>'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/r3_plugin_toolbox-0.4.2/lib/r3_plugin_toolbox.rb:6:in `require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/r3_plugin_toolbox-0.4.2/lib/r3_plugin_toolbox.rb:6:in `<top (required)>'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/devise-links-0.2.3/lib/devise-links/rails/configure.rb:2:in `require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/devise-links-0.2.3/lib/devise-links/rails/configure.rb:2:in `<top (required)>'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/devise-links-0.2.3/lib/devise-links.rb:9:in `require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/devise-links-0.2.3/lib/devise-links.rb:9:in `<top (required)>'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/cream-0.9.2/lib/cream.rb:4:in `require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/cream-0.9.2/lib/cream.rb:4:in `<top (required)>'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.0.14/lib/bundler/runtime.rb:68:in `require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.0.14/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.0.14/lib/bundler/runtime.rb:66:in `each'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.0.14/lib/bundler/runtime.rb:66:in `block in require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.0.14/lib/bundler/runtime.rb:55:in `each'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.0.14/lib/bundler/runtime.rb:55:in `require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/bundler-1.0.14/lib/bundler.rb:120:in `require'
        from D:/Documents/Klatreboks/source/config/application.rb:7:in `<top (required)>'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/commands.rb:15:in `require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/commands.rb:15:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

I noticed rspec wasn't installed when I ran bundle install, so I installed it manually (latest version rspec-core 2.6.4), but this didn't help.

**Comment by stylpe** [comment]
Okay, I just tried adding rspec to my Gemfile, which makes it do this instead:

```
$ rails g cream:full_config
(eval):33:in `create_initializer': undefined method `overwrite' for #<File:0x43f1da8> (NoMethodError)
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/cream-0.9.2/lib/generators/cream/full_config/full_config_generator.rb:121:in `cream_initializer'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/cream-0.9.2/lib/generators/cream/full_config/full_config_generator.rb:63:in `execute_generator'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/cream-0.9.2/lib/generators/cream/full_config/full_config_generator.rb:50:in `main'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `block in invoke_all'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `each'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `map'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:124:in `invoke_all'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/group.rb:226:in `dispatch'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/generators.rb:163:in `invoke'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/commands/generate.rb:10:in `<top (required)>'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `block in require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `block in load_dependency'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
        from d:/Rubies/Ruby192/lib/ruby/gems/1.9.1/gems/railties-3.0.7/lib/rails/commands.rb:17:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

It also seems to have created an empty file config/initializers/cream.rb

**Comment by kristianmandrup** [comment]
For Rspec 2 beta and sometime onwards, it used to be that you had to require 'rspec/core' instead of simply 'rspec'.
I think with the latest Rspec releases, this has been dropped. Either use Rspec < 2.5 or patch the r3_plugin_xxx and company. There shouldn't be runtime dependency on rspec anyways! That is an old bug on my part!
You are most welcome to help weed out bugs like this and send me pull requests. Thanks!

**Comment by stylpe** [comment]
Changing the require to 'rspec' didn't change anything else. It still fails the same way: Same LoadError when the Gemfile doesn't have rspec, and same undefined method 'overwrite' when it does.. For now, I don't mind depending on rspec, though.

But I still can't figure out the second error I posted. The only thing I found out is that it's very sismilar to [this bug](https://github.com/kristianmandrup/cream-app-mongoid/issues/1)

**Comment by kristianmandrup** [comment]
Oh, I think its an issue with a recent upgrade of sugar-high gem which it depends on. Find the overwrite method there and make sure it works (spec) and that it is available as both class and instance method. Sorry!

**Comment by kristianmandrup** [comment]
Another solution is to use a previous version of sugar-high, fx version 0.4.3. I hope to fix this ASAP ;)

**Comment by kristianmandrup** [comment]
Actually, I think you might need to patch with this if you use the latest sugar-high:

File.mutate_ext :all

It basically extends the File class with all the mutation extensions. I did this redesign in order to allow greater flexibility, where before it was all or nothing. Didn't get this into cream yet though. Check the _overwrite_content_spec.rb_ in _sugar-high_.

require 'sugar-high/file_mutate'
File.mutate_ext :all

Then you should be set to go ;)
